### PR TITLE
chore(deps): use `babel-preset-env` instead of `babel-preset-es2015`

### PR DESCRIPTION
**Pull request by probil**
`babel-preset-es2015` is deprecated
https://babeljs.io/env/

### CODE REVIEW

**Comment by ericmdantas** [comment]
Hey, @probil. The latest version (v1.3.2) still has `babel-preset-es2015` as a dependency - is this intended?

It was causing my app to break, because I don't have it installed. Thanks!

**Comment by probil** [comment]
@ericmdantas 
Thanks for your feedback. I will publish `1.3.3` soon with newest `package.json`

**Comment by probil** [comment]
@ericmdantas 
I've just published `v1.3.3` with the fix. Please, verify and let me know.
In any case this is dev dependency so it should not cause any issues

**Comment by ericmdantas** [comment]
Thanks for the quick reply, @probil. I appreciate it.

The error I was getting was: 
```
Couldn't find preset "es2015" relative to directory ${PATH_TO_V_MASK}
```

Now I'm getting a different one:
```
ERROR in ./node_modules/v-mask/dist/v-mask.esm.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "transform-runtime" specified in "${PATH_TO_V_MASK}.babelrc" 
at 0, attempted to resolve relative to "${PATH_TO_V_MASK}"
```

Maybe you should have babel stuff as `dependencies` instead of `devDependencies`? So it's installed as a dep of `v-mask`.

Thanks once again.

**Comment by probil** [comment]
@ericmdantas Your issue is probably related to webpack/browserify/etc configuration

As you can see there is nothing else related to `es2015`
https://cdn.jsdelivr.net/npm/v-mask@1.3.3/package.json

**Pull request merged**
