### PR TITLE
feat(directive): add ability to accept function as a mask

### PR DESCRIPTION
**Pull request by dougiefresh49**
## Overview
Adds the ability to accept a function for mask. Essential for using `createNumberMask` or anything else that cannot be achieved via the simple string

## Uses
```js
// masks.js
import createNumberMask from 'text-mask-addons/dist/createNumberMask';

export const currencyMask = createNumberMask({
    prefix: '$',
    allowDecimal: true,
    includeThousandsSeparator: true,
    allowNegative: false 
});
```
...
```vue
// vue component
<template>
    <input
          :placeholder="placeholder" 
          v-model="valueModel"
          v-mask="currencyMask"
        />
</template>
```

## Addressed Issues 
#15

### CODE REVIEW

**Comment by probil** [comment]
Thanks @dougiefresh49 
I'll check and merge soon

**Comment by hash-bang** [comment]
Any updates on getting this merged?

Very much a wanted feature from me.

**Comment by probil** [comment]
@dougiefresh49 Great work, but could you please remove changes in `dist/*` folder?

**Comment by theianjohnson** [comment]
Would also love to use this, but need number (both currency and not) support 👍

**Comment by Herz3h** [comment]
Any update on this ? @probil

**Comment by probil** [comment]
Unfortunately I've merged another Pull Request which implemented the same functionality. Check release `v2.2.0`

Anyway, thanks for your contribution @dougiefresh49 . There are other places where it can be partially used instead, e.g. README and tests.

**Pull request closed without merging**
