### PR TITLE
Checks for value change before updating input

### PR DESCRIPTION
**Pull request by exlexer**
This is a fix for https://github.com/probil/v-mask/issues/460

`@input` will still call twice when masking changes the value, however, it removes unnecessary updating of unchanged value.

### CODE REVIEW

**Comment by ilyakamens** [comment]
Would love for this to be merged.

**Comment by diego-lipinski-de-castro** [comment]
I tested this locally and it didnt work?

**Comment by exlexer** [comment]
@diego-lipinski-de-castro what functionality are you seeing errors in?

**Comment by diego-lipinski-de-castro** [comment]
If you put a watch on the v-model attached to the input, it will update twice

**Comment by probil** [comment]
The fix is not that easy. Since vue doesn't provide a way to hook into a v-model update functionality it would be hard to fix this. The reason why it's triggered twice is because first one is performed my `v-mask` and the second one by `vue` (v-model). As I know there is no a simple way for `v-mask` to tell `vue` not to update input value (again)

**Pull request closed without merging**
