### PR TITLE
Fix issue #392 not changed value mask

### PR DESCRIPTION
**Pull request by JosielFaleiros**
This pull request is to fix the problem found in the issue #392 , where the value do not get masked when the same value is pasted twice, but it should apply the mask in that case.

This code is working on a local build, and within a project where I am using this lib.

Improvement suggestions are welcome. :)

### CODE REVIEW

**Comment by probil** [comment]
@JosielFaleiros
Can you add tests as well please?

**Comment by JosielFaleiros** [comment]
Hi @probil 

I would like to, but I am little busy these days, this will take some time, so any help from other devs for this are welcome too.

Thanks for the project!

**Comment by JosielFaleiros** [comment]
Hi @probil 

I've added a test to verify the case explained, that will be fixed by this PR.
I hope you find it valid now.

**Comment by probil** [comment]
Hey @JosielFaleiros 
I've check your PR and it works well for your case but doesn't work for another case.
It's impossible to remove placeholder symbol from the input.

1) Let's say I have mask `##:##`
2) I have entered `1111`, value became 
2) I pressed backspace 2 times

**Comment by probil** [comment]
https://github.com/probil/v-mask/pull/415

**Pull request closed without merging**
