### PR TITLE
Improviments implemented to fix cursor position and always mask a input element

### PR DESCRIPTION
**Pull request by yusser**
Hi,

i'm using custom input provided bu ementui for vue and some trobles was founded. I fixed it. Maybe you aprove it. 

I don't know how create elements dinamically to improve the tests, Then, coverage isn't good.

### CODE REVIEW

**Comment by probil** [comment]
`eslint` should be separate PR

**Comment by probil** [comment]
One feature - one PR

**Comment by yusser** [comment]
Ok

**Comment by yusser** [comment]
What may i do to get better PR? Guide me.

**Comment by probil** [comment]
One PR for issue you have fixed + tests for that fix
Don't know why you have added babel-cli, skip it
One more PR with eslint + description why it's needed
Closed due inactivity

**Pull request closed without merging**
