### PR TITLE
Added support for add/remove of custom placeholders, inline RegExp array masks, and functions as masks

### LINKED ISSUE #128: Ability to define mask placeholders
It would be nice to have ability to add/remove/replace custom mask placeholders. 
Predefined placeholders are not enough in some cases. 
Currently the idea is to pass placeholder definitions to the plugin options. This will apply to all masks.

```js
Vue.use(VueMask, { 
  placeholders: {
    // define new placeholder
    'S':  /[a-z]/.test,

    // remove existing placeholder
    '#': null,

    // replace existing placeholder
    'N':  /[a-z]/.test,
    },
  },
});
```

Plus we should be able to do the same for one mask only.
```vue
<template>
  <input v-mask="['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]" />
</template>
```

TODO:
 - [ ] Accepts array of regular expression directly
 - [ ] Add/remove/replace global mask placeholders
 - [ ] Update README

Test cases: 
 - Test for uppercase/lowercase values #67 (3 likes)
 - Test for cyrillic characters #230 (4 likes)
 - Correct time mask #443
 - Ability to define mask like `0(6|7)-##-##-##-##` #184 (5 likes)

### PR DESCRIPTION
**Pull request by davismcphee**
This PR resolves #128 by providing support for add/remove of global mask placeholders, inline RegExp array masks, and passing functions as masks. Also added tests for all test cases listed in the issue.

### CODE REVIEW

**Comment by rafaelmaiach** [comment]
Will this PR be merged?
I'm needing the v-mask accepting array on a project and it would fit perfectly!

**Comment by davismcphee** [comment]
The inline array mask accepts an array of RegExp and strings that make up a single mask. It won't allow you to define multiple masks for the same input. For example: 
```
<input v-mask="[/\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/]"> // '123456' => '123-456'
```

You could use a mask function to choose one of multiple masks though:
```
Vue.component('my-masked-input', {
  data() { 
    return { value: '123456' } ;
  },
  template: '<input v-mask="maskFn" v-model="value" />',
  methods: {
    maskFn(value) {
      if (someCondition) {
        return [/\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/]; // '123456' => '123-456'
      } else {
        return [/\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/]; // '123456' => '12-34-56'
      }
    }
  }
});
```

**Comment by cendrizzi** [comment]
This seems really nice. Would love to see this merged.

**Comment by probil** [comment]
Wow! @davismcphee 
This is awesome. I highly appreciate your effort.

I didn't have time to maintain the library actively for the last 6 months and it turned out there are a lot thing nice stuff. I'll pull your PR and run all the check locally. There are also a couple of places not covered by tests. But besides from that MR looks really good!

**Comment by probil** [comment]
Merged in #479.
Thanks again @davismcphee

**Comment by davismcphee** [comment]
@probil I'm happy to help. Thanks for the great library!

**Pull request closed without merging**
