### PR TITLE
Allow first mask character to not be special

### PR DESCRIPTION
**Pull request by JavierMartinz**
It fixes the first mask character bug for `Vue 1.x`. It was already fixed for `v2` in https://github.com/probil/v-mask/commit/ae23140e5cd91af11e10a3d0200ecc442764effb

### CODE REVIEW

**Comment by probil** [comment]
Thanks for PR, @JavierMartinz I will check and merge soon

**Comment by probil** [comment]
Can you please rebuild and include the result as well?

**Comment by JavierMartinz** [comment]
@probil I think you got it wrong 😄  this PR is for `vue-1.x` branch, so the "build" is the own `index.js`

**Comment by probil** [comment]
@JavierMartinz Merged. Maybe we develop format method independently. So we don't have to port the changes every time to `vue-1.x`

**Pull request merged**
